config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books, only: [:index,:show, :edit, :update]
  resources :author_books
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :author_books
  has_many :books, through: :author_books
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :author_books
  has_many :authors, through: :author_books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author_books_controller.rb
class AuthorBooksController < ApplicationController
  before_action :find_author_book, only:[:show, :edit, :update, :destroy]
def show
  #empty
  @authors = Author.all
  @books = Book.all
end

def new
  @author_book = AuthorBook.new(author_book_params)
end

def create
  @author_book = AuthorBook.new(author_book_params)
  @author_book.save
  redirect_to @authorship.book 
end

def edit
@authors = Author.all
@books = Book.all
end

def update
  @author_book.update(author_book_params)
  redirect_to @author_book
end

def destroy
@author_book.destroy
redirect_to book_path
end

private
def find_author_book
  @author_book = AuthorBook.find(params[:id])
end
def author_book_params
  params.require(:author_book).permit(:author_id, :book_id)
end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only:[:show, :edit, :update, :destroy]

  def index
    @authors = Author.all
  end

  def show
    #empty because of before_action
  end

  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    if @author.valid?
      @author.save
      redirect_to @author
    else
      render :new
    end
  end

  def edit
    #calls before_action
  end

  def update
    @author.update(author_params)
    redirect_to @author
  end

  def destroy
    @author.destroy
    redirect_to authors_path
  end

  private
  def find_author
    @author = Author.find(params[:id])
  end
  def author_params
    params.require(:author).permit(:name, :birth_year)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :find_book, only: [:show, :edit, :update]
  def index
    @books = Book.all
  end

  def show
    @authors = Author.all
    @author_books = AuthorBook.all
    @author_book = AuthorBook.new
  end

  def edit

  end

  def update
    @book.update(book_params)
    redirect_to @book
  end

  private
  def find_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :pages)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/_form.html.erb
<%= form_for @author do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :birth_year %>
<%= f.text_field :birth_year %>
<%= f.submit %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit <%= @author.name %></h1>
<%= render 'form' %>

app/views/authors/index.html.erb
<h1>Authors!</h1><br>

<%= link_to "New Author", new_author_path  %>
<br>
<br>
<ul style="list-style-type:disc">
<% @authors.each do |a| %>
<li><%= link_to a.name, a %> (b. <%= a.birth_year %>)</li>
<% end %>
</ul>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'form' %>

app/views/authors/show.html.erb
<h1><%= @author.name %> (b. <%= @author.birth_year %>)</h1>
<br>Books:<br>
<br>
<ul style="list-style-type:disc">
<% @author.books.each do |book| %>
<li><%= book.title %></li>
<% end %>
</ul>
<%= link_to "Edit #{@author.name}", edit_author_path %>
<%= button_to "Delete #{@author.name}", @author, method: :delete %>

app/views/books/index.html.erb
<h1>Books!</h1><br>
<ul type="list-style-type:disc">
<% @books.each do |book| %>
<li><%= link_to book.title, book %></li>
<% end %>
</ul>

app/views/books/show.html.erb
<h1> <%= @book.title %> (<%=@book.pages %> pages) </h1>
<h2>Authors:</h2>
<ul>
  <% @book.author_books.each do |author_book|%>
  <li><%= link_to author_book.author.name, author_book.author %> (b. <%= author_book.author.birth_year %>)</li>
  <%= button_to "Remove author", author_book, :method => :delete %>
  <% end %>

  <%= form_for @author_book do |f|%>
  <%= f.label :author_id %>
  <%= f.collection_select :author_id, @authors, :id, :name %>
  <%= f.hidden_field :book_id, :value => @book.id %>
  <%= f.submit %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OurProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ol type="1">
    <li><%= link_to "Authors Index", authors_path %></li>
    <li><%= link_to "Books Index", books_path %>
      <hr>
    <%= yield %>
    </ol>


  </body>
</html>